// Generated by CoffeeScript 1.6.3
define(function(require, exports) {
  var cacheElem, cover, dragging, get_positions, local, make_point, size;
  local = {};
  size = require('./size');
  cover = $('#cover');
  make_point = function() {
    var elem, pos;
    elem = $("<div class='point'>" + (cover.children().length) + "</div>");
    pos = size.random_position();
    elem.css('top', "" + pos.y + "px");
    elem.css('left', "" + pos.x + "px");
    cover.append(elem);
    return elem.on('dragstart', function(event) {
      return console.log(elem, event);
    });
  };
  make_point();
  make_point();
  get_positions = function() {
    return $.map($('#cover').children(), function(child) {
      return {
        x: parseInt($(child).css('left')),
        y: parseInt($(child).css('top'))
      };
    });
  };
  $('#increase').click(function() {
    make_point();
    return local.notify(get_positions());
  });
  $('#decrease').click(function() {
    cover.children().last().off().remove();
    return local.notify(get_positions());
  });
  dragging = false;
  cacheElem = null;
  $('#cover').mousedown(function(event) {
    if ($(event.target).is('.point')) {
      dragging = true;
      return cacheElem = $(event.target);
    }
  });
  $('#cover').mouseup(function() {
    dragging = false;
    return cacheElem = null;
  });
  $('#cover').mousemove(function(event) {
    if (dragging) {
      cacheElem.css('left', "" + event.x + "px");
      cacheElem.css('top', "" + event.y + "px");
      return local.notify(get_positions());
    }
  });
  exports.listen = function(handler) {
    return local.notify = handler;
  };
  exports.demo = function() {
    return local.notify(get_positions());
  };
  return exports;
});

/*
//@ sourceMappingURL=drag.map
*/
