// Generated by CoffeeScript 1.6.3
define(function(require, exports) {
  var animate, bend, local, renderer, size, stage, thing;
  size = require('./size');
  bend = require('./bend');
  renderer = PIXI.autoDetectRenderer(size.w, size.h);
  stage = new PIXI.Stage(0xFFFFFF, true);
  $('#paper').append(renderer.view);
  thing = new PIXI.Graphics();
  stage.addChild(thing);
  local = {};
  local.points = [];
  local.caches = [];
  animate = function() {
    var first;
    thing.clear();
    thing.lineStyle(1, 0x4444aa, 1);
    first = local.caches[0];
    if (first != null) {
      thing.moveTo(first.x, first.y);
    }
    local.caches.slice(1).forEach(function(point) {
      return thing.lineTo(point.x, point.y);
    });
    renderer.render(stage);
    return requestAnimationFrame(animate);
  };
  animate();
  exports.set_points = function(points) {
    var tmp;
    local.points = points;
    tmp = points.concat();
    [1, 2, 3, 4, 5].forEach(function() {
      return tmp = bend(tmp, points);
    });
    return local.caches = tmp;
  };
  return exports;
});

/*
//@ sourceMappingURL=render.map
*/
